workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      android: latest
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
      
      - name: Get Flutter packages
        script: |
          flutter pub get
        
      - name: Flutter analyze
        script: |
          flutter analyze
        
      - name: Build APK
        script: |
          flutter build apk --release
        
    artifacts:
      - build/**/outputs/apk/**/*.apk
      
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $FIREBASE_APP_ID
          groups: 
            - beta-testers