workflows:
  web-workflow:
    name: Web Workflow
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: 3.16.5
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Enable Web
        script: flutter config --enable-web
        
      - name: Build Web
        script: flutter build web --release
        
    artifacts:
      - build/web/**
    
    publishing:
      email:
        recipients:
          - kengyap@upm.edu.my
