workflows:
  default-workflow:  # 改成 default 工作流
    name: Flutter CI/CD Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      android: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Build APK
        script: flutter build apk --release
        
    artifacts:
      - build/**/outputs/apk/**/*.apk
      
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $FIREBASE_APP_ID
          groups: 
            - beta-testers
